### ISSUE TITLE
Error popup when launching Wearable Emulator

### ISSUE THREAD

**Issue by JoonghyunCho** [Samsung/Tizen.NET#2]
### Description
The error popup shows after starting Tizen 4.0 Wearable Emulator.
It says "Extra package installation is failed. sap must be installed MANUALLY!".
![image](https://user-images.githubusercontent.com/14328614/55471277-57a97900-5644-11e9-8dd4-55727829680c.png)

### Cause
The popup shows since I have installed  `Samsung Wearable Extension`.
![image](https://user-images.githubusercontent.com/14328614/55471146-12854700-5644-11e9-882f-cf342395e64f.png)

### Environment
Tizen Studio version: 3.2

**Comment by rookiejava** [comment]
@sangwook96-lee PTAL

**Comment by winstone77** [comment]
This issue might be caused by failure of sap related package installation. 
Sap related RPMs should be installed on first wearable emulator launching after installation of wearable extension.
But when we check the emulator log, some rpm installation was failed. 
We are checking this issue with wearable extension developers and will update it soon.

**Comment by rookiejava** [comment]
@winstone77 any updates on this?

**Comment by winstone77** [comment]
This issue has fixed in latest samsung wearable extension (v1.4.1). 
You can verify it with update of tizen-studio and extra packages.

**Comment by EmilAlipiev** [comment]
how is it fixed on   samsung wearable extension (v1.4.1)? I am having it but i still get this error. what is the proper solution here please?
